version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ansible
    versions:
    - 2.10.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
