---

- name: Installing needed packages
  become: true
  package:
    name: "{{ iptables_packages }}"
    state: present
    update_cache: true

- name: Copy firewall script into place.
  template:
    src: docker-hardening.bash.j2
    dest: /etc/docker-hardening.bash
    owner: root
    group: root
    mode: 0744

- name: Copy firewall init script into place.
  template:
    src: docker-hardening.init.j2
    dest: /etc/init.d/docker-hardening
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"

- name: Copy firewall systemd unit file into place (for systemd systems).
  template:
    src: docker-hardening.unit.j2
    dest: /etc/systemd/system/docker-hardening.service
    owner: root
    group: root
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: Activate Rules
  become: true
  shell: /etc/docker-hardening.bash
